# These are supported funding model platforms

github: [lmliheng, lieheng-1]
patreon: liheng
open_collective: liheng
ko_fi: liheng
tidelift: npm/babel
community_bridge: cloud-foundry
liberapay: liheng
issuehunt: liheng
lfx_crowdfunding: cloud-foundry
polar: liheng
buy_me_a_coffee: liheng
custom: ['https://paypal.me/lmliheng', 'http://home.liheng.work']
