language: c

sudo: false

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

script: make CC="$CC" LD="$CC" && make check

matrix:
  include:
    - os: linux
      compiler: i586-mingw32msvc-gcc
      script: make CC="$CC" XCFLAGS= LD="$CC"
    - os: linux
      compiler: '"clang -fsanitize=address"'
      script: make CC="$CC" LD="$CC" && make check
    - os: linux
      compiler: '"clang -fsanitize=memory"'
      script: make CC="$CC" LD="$CC" && make check

